### ISSUE TITLE
Please add a mode line indicator 

### ISSUE THREAD

**Issue by pointsman** [nflath/hungry-delete#18]
While I mostly enjoy to have hungry-delete turned on sometimes I just want normal delete behaviour. It's easily turned on and off, no question (I even have a global key binding for that), but what I miss is to see somewhere if it's currently on or off.

A small mode line indicator, if hungry-delete mode is on, would be the natural place for that.

A simple an small "h" (as cc-mode does, if hungry delete is turned on) would be sufficent.

**Comment by mwfogleman** [comment]
See pull #19 .

**Comment by pointsman** [comment]
Thanks. That will do it.
