### ISSUE TITLE
hungry deleting newlines as well should be possible

### ISSUE THREAD

**Issue by sooheon** [nflath/hungry-delete#20]
Similar to how `just-one-space` takes a negative arg to handle newlines as well. It'd be great if it was a variable setting, rather than polluting the prefix arg space. I find while coding you almost never want to just hungry delete to the beginning of line (that would just be messing up indentation), but to join lines.

In the c-hungry-delete description, it says it also deletes newlines as well: http://www.gnu.org/software/emacs/manual/html_node/ccmode/Hungry-WS-Deletion.html

**Comment by nflath** [comment]
I don't quite understand the issue you're having - do you have an example you can reproduce in a blank emacs session with only hungry-delete working?  It deletes newlines for me.

**Comment by sooheon** [comment]
My bad, I can see how with all other config disabled this desired behavior is there. So the issue is with my own config. Sorry!

**Comment by NightMachinary** [comment]
@nflath Is there a way to disable deleting newlines?

**Comment by nflath** [comment]
You can configure hungry-delete-chars-to-skip to not have newlines - try  (setq hungry-delete-chars-to-skip " \t\r\f\v")
