### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by mdorman** [nflath/hungry-delete#22]
If you would just drop a tag in the repo, melpa-stable would pick it up.  marmalade is pretty moribund, melpa-stable serves a very similar purpose, though.

**Comment by nflath** [comment]
Sounds good - how do I do this?

**Comment by mdorman** [comment]
Just add a git tag:

git tag 1.1.2 # assumes that the 1.1.2 in the .el file is the correct version :)
git push --tags # makes sure that tags get set on github

**Comment by nflath** [comment]
OK, done I think :)  Thanks!

**Comment by mdorman** [comment]
Yep, worked fine, it's now on stable.melpa.org.  Thanks!
