### ISSUE TITLE
Backslash at end of line shouldn't always be considered whitespace

### ISSUE THREAD

**Issue by oantolin** [nflath/hungry-delete#23]
Currently hungry-delete deletes both whitespace *and* backslashes at the end of a line. I imagine this is very convient for C preprocessors macros, that often span mutliple lines ending in backslashes. Unfortunately this is very inconvenient in LaTeX, where lines of tables and similar environments can end in double backslash (`\\`). Currently hungry-delete will remove the second backslash!

I'm not sure what the best way to deal with this is. I think checking if the backslash at the end of line has aanother backslash preceding it and in that case not deleting either backslash might be a good rule for all major modes. But maybe it's best to just have the backslash deletion be optional, depending on a buffer local variable. That way users can pick in which modes they want trailing backslashes to be considered "honorary whitespace".

**Comment by nflath** [comment]
Fixed in 1.1.3 - mind testing it?

**Comment by nflath** [comment]
By 'fixed' i mean I added a variable to configure it.

**Comment by oantolin** [comment]
There's a typo in the `defvar` declaration, you wrote: `hyngry-delete-delete-backslash-eol` instead of "hungry". Once that's corrected, the fix does work.

But I've been thinking some more about this and maybe this doesn't need a configuration variable. How about the following rule? A backslash is deleted when it is at the end of a line *and* is preceded immediately by whitespace? I think that would be sensible in all syntaxes I'm aware of.

**Comment by oantolin** [comment]
Here's my proposed implementation of the rule I mentioned:

```elisp
(defun hungry-delete-skip-ws-forward ()
  "Skip over any whitespace following point.
This function skips over horizontal and vertical whitespace and
line continuations."
  (while (and
          (> (skip-chars-forward hungry-delete-chars-to-skip) 0)
          (eq (char-after) ?\\)
          (progn
            (forward-char)
            (or (eolp) (backward-char)))))
  (while (get-text-property (point) 'read-only)
    (backward-char)))

(defun hungry-delete-skip-ws-backward (&optional limit)
  "Skip over any whitespace preceding point.
This function skips over horizontal and vertical whitespace and
line continuations."
  (skip-chars-backward hungry-delete-chars-to-skip)
  (while (and
          (eolp)
          (eq (char-before) ?\\)
          (progn
            (backward-char)
            (or
             (= (point) (point-min))
             (< (skip-chars-backward hungry-delete-chars-to-skip) 0)
             (forward-char)))))
  (while (get-text-property (point) 'read-only)
    (forward-char)))
```

Notice that besides implementing the rule I mentioned I also removed the optional `limit` argument that is never used! (These functions are only ever called through `hungry-delete-impl` that does `(funcall fn)` without passing an argument.) Also, the functions contained plenty of duplication (the entire loop appeared twice!) which I also removed. Even if you don't like the backslash rule I'm proposing and intend to keep the configuration variable, I'd still suggest eliminating the `limit` variable and one copy of each duplicated loop.

**Comment by nflath** [comment]
Using your versions of the functions now.
