### ISSUE TITLE
latest commit breaks hungry-delete-mode

### ISSUE THREAD

**Issue by CSRaghunandan** [nflath/hungry-delete#24]
the latest update broke `hungry-delete-mode`. Whenever I try to delete a character I get the error: `hungry-delete-impl: Symbol’s value as variable is void: hungry-delete-delete-backslash-eol` 

**EDIT**:After looking at `hungry-delete.el` source code, I identified the mistake to be on this line(it's a small typo): 
```
(defvar hyngry-delete-delete-backslash-eol t
  "Whether a backslash at the end of a line will be deleted.")
```

**Comment by oantolin** [comment]
I think that was indirectly my fault, as Nathan added that variable due to an issue I raised: #23.

**Comment by CSRaghunandan** [comment]
@oantolin Ah I see it was already reported in another closed issue. woops my bad.
