### ISSUE TITLE
hungry delete in alterative binding

### ISSUE THREAD

**Issue by rhoit** [nflath/hungry-delete#31]
Mapping the **hungry-delete** to default **delete/backspace** kinda take you by suprize, and have manually toggling the mode, just to delete few continous white spaces. Result you barely use it as global mode.

Wouldn't it be nice to add the alternative binding may be **S-&lt;backspace&gt;**  and **S-&lt;delete&gt;**

currently i'm using it as

```
(global-set-key (kbd "S-<backspace>") 'hungry-delete-backward)
```

although I have yet to figure out **S-&lt;delete&gt;** its bindind to *kill-region* which requires selected region.

**Comment by nflath** [comment]
I definitely prefer it as replacing those keys....What you're doing seems fine as well but I don't see a reason to change what it does now.
