### ISSUE TITLE
Delete rectangular selection

### ISSUE THREAD

**Issue by seregaxvm** [nflath/hungry-delete#33]
In `hungry-delete-mode` when there's a rectangular selection (`rectangle-mark-mode`):
![image](https://user-images.githubusercontent.com/26824900/75875738-56209c00-5e25-11ea-98bd-ed66c50283aa.png)
`hungry-delete-forward` and `hungry-delete-backward` remove all text between markers, not just the selection.
![image](https://user-images.githubusercontent.com/26824900/75875823-81a38680-5e25-11ea-896f-8908b0efbb30.png)

**Comment by nflath** [comment]
Should be fixed now, let me know if that doesn't work.

**Comment by seregaxvm** [comment]
Solution relies of variable `cua--rectangle`, which is not good. I don't use `cua-mode`, so for me this symbol value is void and I get a runtime error.
