### ISSUE TITLE
cua--rectangle

### ISSUE THREAD

**Issue by slk500** [nflath/hungry-delete#37]
After reinstall Emacs I got this error when I press "Delete". 
"Debugger entered--Lisp error: (void-variable cua--rectangle)
  hungry-delete-forward(1 nil)
  funcall-interactively(hungry-delete-forward 1 nil)
  call-interactively(hungry-delete-forward nil nil)
  command-execute(hungry-delete-forward)"
Any idea how to fix it ?
GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2019-09-28

**Comment by seagle0128** [comment]
I think the solution is #36 .

**Comment by peterwvj** [comment]
I'm experiencing this issue as well. I can confirm that #36 fixes the issue.

**Comment by nflath** [comment]
Merged, sorry about this.

**Comment by peterwvj** [comment]
No need so say sorry.

Thank you for responding quickly to this issue!
