### ISSUE TITLE
delete backward fails when followed by readonly text

### ISSUE THREAD

**Issue by matsievskiysv** [nflath/hungry-delete#40]
`hungry-delete-backward` fails when cursor is positioned right before readonly region. This is an issue when working with [ein](https://github.com/millejoh/emacs-ipython-notebook) notebooks or [text folds](https://github.com/matsievskiysv/vimish-fold)

## Reproduce in `ein` mode
1. create new notebook
1. type some text in cell
1. position cursor at the end of the cell
1. run `hungry-delete-backward` and observe the command fail
1. return cursor to the same position
1. run `delete-backward-char` and observe the desired behavior

## Reproduce with `vimish-fold`
1. open file with some text
1. create fold using `vimish-fold`
1. position cursor at the end of the line preceding text fold 
1. run `hungry-delete-backward` and observe the command fail
1. return cursor to the same position
1. run `delete-backward-char` and observe the desired behavior

**Comment by nflath** [comment]
This should be fixed by https://github.com/nflath/hungry-delete/commit/5b75831602ddac7ee08922a1615ce7f4f165b349#diff-a2b29fd6731dc6737e1bd2b5ee4a7f21 - can you check to make sure it works for you?

**Comment by matsievskiysv** [comment]
Not quite. Removed spaces just fine, but failed to remove character:

![out](https://user-images.githubusercontent.com/26824900/89716524-4ef25100-d9b6-11ea-8753-a95a85cb2947.gif)

**Comment by nflath** [comment]
Intreesting, I haven't been able to reproduce - Can you post detailed instructions using vimish-fold?  It seems to work for me.

**Comment by matsievskiysv** [comment]
Yep, I've tried starting Emacs with command `emacs -q --eval (progn (package-initialize) (use-package vimish-fold) (use-package hungry-delete))` and everything worked. Guess, there's a problem in my config.
